sample/WkeSampleApp/Controllers/InvoicesController.cs
namespace WkeSampleLoadApp.Controllers
{
    using Microsoft.AspNetCore.Mvc;
    using Microsoft.AspNetCore.Mvc.ModelBinding.Metadata;
    using Microsoft.EntityFrameworkCore;
    using WkeSampleLoadApp.a3innuva;
    using WkeSampleLoadApp.Context;

    public class InvoicesController : BaseController
    {
        private readonly WkeSampleLoadAppContext wkeSampleLoadAppContext;

        public InvoicesController(
            IConfiguration configuration,
            WkeSampleLoadAppContext wkeSampleLoadAppContext)
            : base(configuration)
        {
            this.wkeSampleLoadAppContext = wkeSampleLoadAppContext ?? throw new ArgumentNullException(nameof(wkeSampleLoadAppContext));
        }

        // GET: InvoicesController
        public async Task<IActionResult> Index(string companyCorrelationId)
        {

            var invoices = await this.wkeSampleLoadAppContext.Invoices.Where(a => a.CompanyId == new Guid(companyCorrelationId)).OrderBy(a => a.InvoiceDate).ToListAsync();
            ViewBag.CompanyCorrelationId = companyCorrelationId;

            return View(invoices);

        }

        // GET: InvoicesController/Details/5
        public async Task<IActionResult> Details(string companyCorrelationId, string invoiceCorrelationId)
        {
            var invoice = await this.wkeSampleLoadAppContext.Invoices.FirstAsync(r => r.CorrelationId == invoiceCorrelationId);

            ViewBag.CompanyCorrelationId = companyCorrelationId;

            return View(invoice);
        }

        // GET: InvoicesController/Edit/5
        public async Task<IActionResult> Edit(string companyCorrelationId, string invoiceCorrelationId)
        {

            var invoice = await this.wkeSampleLoadAppContext.Invoices.FirstAsync(r => r.CorrelationId == invoiceCorrelationId);

            ViewBag.CompanyCorrelationId = companyCorrelationId;

            return View(invoice);

        }

        // POST: InvoicesController/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit([Bind("CorrelationId, InvoiceDate, AccountCode,Concept, Amount, TaxAmounbt")] ModifyInvoiceCommand modifyInvoiceCommand, string companyCorrelationId)
        {


            var invoice = await this.wkeSampleLoadAppContext.Invoices.FirstAsync(r => r.CorrelationId == modifyInvoiceCommand.CorrelationId);

            invoice.Concept = modifyInvoiceCommand.Concept;
            invoice.AccountCode = modifyInvoiceCommand.AccountCode;
            invoice.Amount = modifyInvoiceCommand.Amount;
            invoice.TaxAmount = modifyInvoiceCommand.TaxAmount;

            await this.wkeSampleLoadAppContext.SaveChangesAsync();

            ViewBag.CompanyCorrelationId = companyCorrelationId;

            return RedirectToAction("Index", new { companyCorrelationId = companyCorrelationId });

        }
    }
}

sample/WkeSampleApp/Views/Invoices/Details.cshtml
@using WkeSampleLoadApp.a3innuva

@model InvoiceModel
@{
    ViewData["Title"] = "Home Page";
    var companyCorrelationId = ViewBag.CompanyCorrelationId;
}

<div class="text-center">
    
    <h1 class="display-4">Factura</h1>
    <hr />

    <div>
        <dl class="row">
            <dt class = "col-sm-2">
                @Html.DisplayNameFor(model => model.InvoiceDate)
            </dt>
            <dd class = "col-sm-10">
                @Html.DisplayFor(model => model.InvoiceDate)
            </dd>
            <dt class = "col-sm-2">
                @Html.DisplayNameFor(model => model.Concept)
            </dt>
            <dd class = "col-sm-10">
                @Html.DisplayFor(model => model.Concept)
            </dd>
            <dt class="col-sm-2">
                @Html.DisplayNameFor(model => model.AccountCode)
            </dt>
            <dd class="col-sm-10">
                @Html.DisplayFor(model => model.AccountCode)
            </dd>
            <dt class="col-sm-2">
                @Html.DisplayNameFor(model => model.Amount)
            </dt>
            <dd class="col-sm-10">
                @Html.DisplayFor(model => model.Amount)
            </dd>
            <dt class="col-sm-2">
                @Html.DisplayNameFor(model => model.TaxAmount)
            </dt>
            <dd class="col-sm-10">
                @Html.DisplayFor(model => model.TaxAmount)
            </dd>
        </dl>
    </div>
    <div style="text-align: left;">
        <a asp-action="Index" asp-route-companyCorrelationId="@companyCorrelationId" class="btn btn-default">Back to List</a>
    </div>

</div>

sample/WkeSampleApp/Views/Invoices/Edit.cshtml
@using WkeSampleLoadApp.a3innuva

@model InvoiceModel

@{
    ViewData["Title"] = "Edit";
    Layout = "~/Views/Shared/_Layout.cshtml";
    var companyCorrelationId = ViewBag.CompanyCorrelationId;
}

<h1>Editar</h1>
<h4>Factura</h4>
<hr />

<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <input type="hidden" name="CompanyCorrelationId" value="@companyCorrelationId"/>
            <input type="hidden" asp-for="CorrelationId" value="@Model.CorrelationId"/>            
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Id" />
            <div class="form-group">
                <label asp-for="InvoiceDate" class="control-label"></label>
                @Html.DisplayFor(model => model.InvoiceDate)
            </div>
            <div class="form-group">
                <label asp-for="Concept" class="control-label"></label>
                <input asp-for="Concept" class="form-control" />
                <span asp-validation-for="Concept" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="AccountCode" class="control-label"></label>
                <input asp-for="AccountCode" class="form-control" />
                <span asp-validation-for="AccountCode" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Amount" class="control-label"></label>
                <input asp-for="Amount" class="form-control" />
                @*<span asp-validation-for="Amount" class="text-danger"></span>*@
            </div>
            <div class="form-group">
                <label asp-for="TaxAmount" class="control-label"></label>
                <input asp-for="TaxAmount" class="form-control" />
                @*<span asp-validation-for="TaxAmount" class="text-danger"></span>*@
            </div>
            
            <br />
            <div class="form-group">
                <input type="submit" value="Guardar" class="btn btn-primary" />&nbsp;
                <a asp-action="Index" asp-route-companyCorrelationId="@companyCorrelationId" class="btn btn-default">Volver</a>
            </div>
        </form>
    </div>
</div>

<br />

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

sample/WkeSampleApp/Views/Invoices/Index.cshtml
@using WkeSampleLoadApp.a3innuva

@model List<InvoiceModel>
@{
    ViewData["Title"] = "Home Page";
    var companyCorrelationId = ViewBag.companyCorrelationId;
}

<div class="text-center">
    
    <h1 class="display-4">Lista de facturas</h1>

    <table class="table">
        <thead>
            <tr>
                <td>
                    Fecha
                </td>
                <td style="text-align: left;">
                    Concepto
                </td>
                <td style="text-align: left;">
                    Cuenta
                </td>
                <td>
                    Total
                </td>
                <td>
                    options
                </td>
            </tr>
        </thead>
        <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @item.InvoiceDate
                </td>
                <td style="text-align: left;">
                    @item.Concept
                </td>
                <td style="text-align: left;">
                    @item.AccountCode
                </td>
                <td >
                    @item.Total
                </td>
                <td>
                    @Html.ActionLink("Ver", "Details", "Invoices", new { Area = "", companyCorrelationId = companyCorrelationId, invoiceCorrelationId = item.CorrelationId }, new { @class = "btn" })
                    @Html.ActionLink("Editar", "Edit", "Invoices", new { Area = "", companyCorrelationId = companyCorrelationId, invoiceCorrelationId = item.CorrelationId }, new { @class = "btn" })                        
                </td>
            </tr>
        }
        </tbody>
    </table>

</div>